# Generated by Django 4.2.1 on 2023-05-06 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('current_age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('date_missing', models.DateField()),
                ('photo', models.ImageField(upload_to='missing_children')),
            ],
        ),
        migrations.CreateModel(
            name='ChildPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='missing_children')),
                ('age_at_photo', models.IntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facerec.missingchild')),
            ],
        ),
    ]
