# Generated by Django 4.2.1 on 2023-05-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availablechildphotos',
            name='child',
        ),
    ]
